  Hey There! 
  I am new to GitHub and currently undergoing GitHub trianing.
The conent is awasone and i would like to recommend to every new joiner like me .

Hope you will also enjoy the training and excercies as much as me. 
