title: GitHub a Powerhouse
theme: minima
author: Shrishti Awasthi
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I am new to GitHub and currently undergoing the tranings provided.
  I am enjoying myself , and it is so much fun.
  Material provided is easy to understand.
  
  I hope the feedback will help you , Happy Learning :)
 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
