author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hey There! 
  I am new to GitHub and currently undergoing GitHub trianing.
The conent is awasone and i would like to recommend to every new joiner like me .

Hope you will also enjoy the training and excercies as much as me. 
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
